task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 8
remap_mscoco_category: False


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection_Multimodal
    img_folder: images_co
    ann_file: train_co.json
    pair_mode: vedai
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion_Multimodal


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection_Multimodal
    img_folder: images_co
    ann_file: test_co.json
    pair_mode: vedai
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion_Multimodal
