task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 6
remap_mscoco_category: False


train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection_Multimodal
    img_folder: images_vi
    ann_file: train.json
    pair_mode: m3fd
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion_Multimodal


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection_Multimodal
    img_folder: images_vi
    ann_file: test.json
    pair_mode: m3fd
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion_Multimodal
